//! Per-CLI adapters — how to launch, capture the CLI's session ID, and resume.
//! SPEC.md §5 is the normative table. Phase 2 implements.

#![allow(dead_code)] // Phase 1 skeleton

pub mod claude;
pub mod codex;
pub mod copilot;
pub mod opencode;
pub mod terminal;

use crate::models::{Session, Tool};

/// A concrete command line to spawn inside a PTY.
pub struct SpawnSpec {
    pub program: String,
    pub args: Vec<String>,
    /// cwd is always the session's folder path; recorded here for clarity.
    pub cwd: String,
}

/// How a session's CLI session ID becomes known.
pub enum IdCapture {
    /// ID generated by Anchor and passed on the launch command line
    /// (claude `--session-id`, copilot `--resume <fresh-uuid>`).
    PreAssigned(String),
    /// ID must be discovered from the CLI's own session store after launch
    /// (codex jsonl files, opencode sqlite). See `discover_session_id`.
    Discover,
    /// Not applicable (generic terminal).
    None,
}

pub trait Adapter {
    fn tool(&self) -> Tool;

    /// Build the launch command. For pre-assigning tools this also decides the
    /// cli_session_id (returned via IdCapture::PreAssigned).
    fn launch(&self, session: &Session) -> Result<(SpawnSpec, IdCapture), String>;

    /// Build the resume command. If `session.cli_session_id` is None, return
    /// the CLI's interactive-picker fallback (SPEC.md §5) — never an error.
    fn resume(&self, session: &Session) -> Result<SpawnSpec, String>;

    /// Poll the CLI's session store for a session matching this record
    /// (cwd + created ≥ launch time). Returns Ok(None) while pending.
    /// Only meaningful for IdCapture::Discover tools; default: not applicable.
    fn discover_session_id(&self, session: &Session) -> Result<Option<String>, String> {
        let _ = session;
        Ok(None)
    }
}

pub fn adapter_for(tool: Tool) -> Box<dyn Adapter + Send + Sync> {
    match tool {
        Tool::Claude => Box::new(claude::ClaudeAdapter),
        Tool::Codex => Box::new(codex::CodexAdapter),
        Tool::Copilot => Box::new(copilot::CopilotAdapter),
        Tool::Opencode => Box::new(opencode::OpencodeAdapter),
        Tool::Terminal => Box::new(terminal::TerminalAdapter),
    }
}
