//! Per-CLI adapters translate Anchor sessions into CLI commands and inspect
//! version-fragile CLI stores without exposing those details to orchestration.

#![allow(dead_code)] // Used by later Phase 2 orchestration tasks.

pub mod claude;
pub mod codex;
pub mod copilot;
pub mod opencode;
pub mod terminal;

use std::path::{Path, PathBuf};
use std::time::SystemTime;

use crate::models::{Session, Settings, Tool};

/// A concrete command line to spawn inside a PTY.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpawnSpec {
    pub program: String,
    pub args: Vec<String>,
    pub cwd: PathBuf,
    /// Directory of the resolved CLI launcher. This differs from `program`
    /// when Windows runs a `.cmd` shim through `cmd.exe`.
    pub launcher_directory: Option<PathBuf>,
}

impl SpawnSpec {
    pub fn new<I, S>(program: impl Into<String>, args: I, cwd: impl Into<PathBuf>) -> Self
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        Self {
            program: program.into(),
            args: args.into_iter().map(Into::into).collect(),
            cwd: cwd.into(),
            launcher_directory: None,
        }
    }
}

/// How a session's CLI session ID becomes known.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IdCapture {
    /// ID generated by Anchor and passed on the launch command line
    /// (claude `--session-id`, copilot `--resume <fresh-uuid>`).
    PreAssigned(String),
    /// ID must be discovered from the CLI's own session store after launch
    /// (codex jsonl files, opencode sqlite). See `discover_session_id`.
    Discover,
    /// Not applicable (generic terminal).
    None,
}

pub trait Adapter {
    fn tool(&self) -> Tool;

    /// Build the launch command. For pre-assigning tools this also decides the
    /// cli_session_id (returned via IdCapture::PreAssigned).
    fn launch(
        &self,
        session: &Session,
        cwd: &Path,
        settings: &Settings,
    ) -> Result<(SpawnSpec, IdCapture), String>;

    /// Build the resume command for the exact persisted CLI session.
    ///
    /// AI adapters must never emit an interactive-picker command: requiring
    /// manual session selection would break Anchor's one-click resume promise.
    fn resume(
        &self,
        session: &Session,
        cwd: &Path,
        settings: &Settings,
    ) -> Result<SpawnSpec, String>;

    /// Poll the CLI's session store for a session matching this record
    /// (cwd + created ≥ launch time). Returns Ok(None) while pending.
    /// Only meaningful for IdCapture::Discover tools; default: not applicable.
    fn discover_session_id(
        &self,
        cwd: &Path,
        launched_at: SystemTime,
    ) -> Result<Option<String>, String> {
        let _ = (cwd, launched_at);
        Ok(None)
    }
}

pub fn adapter_for(tool: Tool) -> Box<dyn Adapter + Send + Sync> {
    match tool {
        Tool::Claude => Box::new(claude::ClaudeAdapter::default()),
        Tool::Codex => Box::new(codex::CodexAdapter::default()),
        Tool::Copilot => Box::new(copilot::CopilotAdapter),
        Tool::Opencode => Box::new(opencode::OpencodeAdapter::default()),
        Tool::Terminal => Box::new(terminal::TerminalAdapter),
    }
}

pub(crate) fn session_id_for_resume(session: &Session, tool: Tool) -> Result<&str, String> {
    session
        .cli_session_id
        .as_deref()
        .filter(|id| !id.is_empty())
        .ok_or_else(|| {
            format!(
                "SESSION_ID_UNAVAILABLE: saved {} session has no CLI session ID",
                tool_name(tool)
            )
        })
}

pub(crate) fn validate_extra_args(tool: Tool, args: &[String]) -> Result<(), String> {
    let option_args = args
        .iter()
        .position(|argument| argument == "--")
        .map_or(args, |delimiter| &args[..delimiter]);
    let changes_identity = match tool {
        Tool::Claude => {
            has_flag(
                option_args,
                &["--session-id", "--resume", "--continue", "-r", "-c"],
            ) || has_attached_short_value(option_args, &["-r"])
        }
        Tool::Copilot => {
            has_flag(option_args, &["--resume", "-r"])
                || has_attached_short_value(option_args, &["-r"])
        }
        Tool::Opencode => {
            has_flag(option_args, &["--session", "-s"])
                || has_attached_short_value(option_args, &["-s"])
        }
        Tool::Codex => {
            option_args.iter().any(|arg| {
                matches!(arg.as_str(), "resume" | "fork" | "--profile" | "-p")
                    || arg.starts_with("--profile=")
            }) || has_attached_short_value(option_args, &["-p"])
        }
        Tool::Terminal => false,
    };
    if changes_identity {
        // Extra args may contain credentials or prompts, so validation errors
        // identify only the tool and never echo the rejected values.
        Err(format!(
            "INVALID_EXTRA_ARGS: {} launch arguments cannot change session identity",
            tool_name(tool)
        ))
    } else {
        Ok(())
    }
}

fn has_attached_short_value(args: &[String], flags: &[&str]) -> bool {
    args.iter().any(|argument| {
        flags
            .iter()
            .any(|flag| argument.starts_with(flag) && argument.len() > flag.len())
    })
}

fn has_flag(args: &[String], flags: &[&str]) -> bool {
    args.iter().any(|argument| {
        flags.iter().any(|flag| {
            argument == flag
                || (flag.starts_with("--")
                    && argument
                        .strip_prefix(flag)
                        .is_some_and(|suffix| suffix.starts_with('=')))
        })
    })
}

fn tool_name(tool: Tool) -> &'static str {
    match tool {
        Tool::Claude => "claude",
        Tool::Codex => "codex",
        Tool::Copilot => "copilot",
        Tool::Opencode => "opencode",
        Tool::Terminal => "terminal",
    }
}

pub(crate) fn paths_match(left: &Path, right: &Path) -> bool {
    let (left, right) = match (std::fs::canonicalize(left), std::fs::canonicalize(right)) {
        (Ok(left), Ok(right)) => (left, right),
        _ => (lexical_normalize(left), lexical_normalize(right)),
    };
    #[cfg(windows)]
    {
        windows_paths_match(&left.to_string_lossy(), &right.to_string_lossy())
    }
    #[cfg(not(windows))]
    {
        left == right
    }
}

fn lexical_normalize(path: &Path) -> PathBuf {
    use std::path::Component;

    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                let can_pop = normalized
                    .file_name()
                    .is_some_and(|name| name != std::ffi::OsStr::new(".."));
                if can_pop {
                    normalized.pop();
                } else if !path.is_absolute() {
                    normalized.push(component.as_os_str());
                }
            }
            _ => normalized.push(component.as_os_str()),
        }
    }
    normalized
}

pub(crate) fn windows_paths_match(left: &str, right: &str) -> bool {
    normalize_windows_path_text(left) == normalize_windows_path_text(right)
}

pub(crate) fn normalize_windows_path_text(path: &str) -> String {
    let replaced = path.replace('\\', "/");
    let without_extended = if replaced
        .get(..4)
        .is_some_and(|prefix| prefix.eq_ignore_ascii_case("//?/"))
    {
        &replaced[4..]
    } else {
        &replaced
    };
    let without_extended = if without_extended
        .get(..4)
        .is_some_and(|prefix| prefix.eq_ignore_ascii_case("UNC/"))
    {
        format!("//{}", &without_extended[4..])
    } else {
        without_extended.to_owned()
    };
    let prefix = if without_extended.starts_with("//") {
        "//"
    } else if without_extended.starts_with('/') {
        "/"
    } else {
        ""
    };
    let mut segments = Vec::new();
    for segment in without_extended.trim_start_matches('/').split('/') {
        match segment {
            "" | "." => {}
            ".." => {
                segments.pop();
            }
            _ => segments.push(segment.to_lowercase()),
        }
    }
    format!("{prefix}{}", segments.join("/"))
}
